import { Suspense } from 'react';																									
																									
type TransactionReport = {																									
Tanggal: string;																									
No Struk: string;																									
Total: number;																									
Bayar: number;																									
Kembalian: number;																									
};																									
																									
async function getReports(): Promise<TransactionReport[]> {																									
const res = await fetch('https://script.google.com/macros/s/AKfycbz1uLGpLSVmsmDY5nyyH3I-caM72e2vdKOAFiSnXy8DlyjNndNDJOD2T5QYmFuQZxvo/exec', {																									
next: { revalidate: 30 },																									
});																									
																									
if (!res.ok) {																									
throw new Error('Gagal mengambil data laporan penjualan');																									
}																									
return res.json();																									
}																									
																									
async function ReportDashboard() {																									
const reports = await getReports();																									
const totalOmset = reports.reduce((sum, item) => sum + (Number(item.Total) || 0), 0);																									
																									
return (																									
<div className="space-y-6">																									
<div className="grid grid-cols-1 md:grid-cols-2 gap-6">																									
<div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-emerald-500">																									
<p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Total Pendapatan (Omset)</p>																									
<p className="text-3xl font-black text-gray-900 mt-2">																									
Rp {new Intl.NumberFormat('id-ID').format(totalOmset)}																									
</p>																									
</div>																									
<div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-blue-500">																									
<p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Volume Transaksi Sukses</p>																									
<p className="text-3xl font-black text-gray-900 mt-2">{reports.length} Nota</p>																									
</div>																									
</div>																									
																									
<div className="overflow-x-auto bg-white rounded-xl shadow-sm border border-gray-100">																									
<table className="min-w-full text-left text-sm whitespace-nowrap">																									
<thead className="uppercase tracking-wider border-b border-gray-200 bg-gray-50 text-xs font-semibold text-gray-600">																									
<tr>																									
<th className="px-6 py-4">Waktu Transaksi</th>																									
<th className="px-6 py-4">Nomor Struk</th>																									
<th className="px-6 py-4 text-right">Total Nilai</th>																									
</tr>																									
</thead>																									
<tbody className="divide-y divide-gray-100 text-gray-700">																									
{reports.map((report, index) => (																									
<tr key={index} className="hover:bg-gray-50 transition">																									
<td className="px-6 py-4 text-gray-500">																									
{report.Tanggal ? new Date(report.Tanggal).toLocaleString('id-ID') : '-'}																									
</td>																									
<td className="px-6 py-4 font-mono text-xs font-bold text-blue-600">{report["No Struk"]}</td>																									
<td className="px-6 py-4 text-right font-bold text-gray-900">																									
Rp {new Intl.NumberFormat('id-ID').format(report.Total || 0)}																									
</td>																									
</tr>																									
))}																									
</tbody>																									
</table>																									
</div>																									
</div>																									
);																									
}																									
																									
export default function DashboardPage() {																									
return (																									
<main className="min-h-screen bg-gray-50 p-6 md:p-12">																									
<div className="max-w-6xl mx-auto">																									
<header className="mb-8">																									
<h1 className="text-3xl font-black tracking-tight text-gray-900">Monitoring Kasir</h1>																									
<p className="text-sm text-gray-500 mt-1">Data langsung dari spreadsheet toko</p>																									
</header>																									
<Suspense fallback={<div className="text-center py-20 text-gray-400">Sinkronisasi data transaksi...</div>}>																									
<ReportDashboard />																									
</Suspense>																									
</div>																									
</main>																									
);																									
}																									
}																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									